[package]
name = "Shutterbomb"
version = "0.2.0"
edition = "2024"
authors = ["Your Name <your.email@example.com>"]
description = "📸💣 Shutterbomb - A terminal-based cute application for databending 📸💣"
license = "GPL-3.0-or-later"
repository = "https://github.com/helloimmiguel/Shutterbomb"
homepage = "theafterthought.space/shutterbomb"
readme = "README.md"
keywords = ["databending", "terminal", "cute", "image manipulation"]
categories = ["Utilities", "Image Processing"]


[dependencies]
crossterm = "0.29.0"
image = "0.25.6"
rand = "0.9.2"
ratatui = "0.29.0"

